### ISSUE TITLE
Can't properly filter by nullable primitive datatypes

### ISSUE THREAD

**Issue by Gonzo345** [onebeyond/monaco#39]
Recently found an issue where an Entity offering filtering by nullable properties is not being applied correctly.

The `ValidateDateType` [method](https://github.com/onebeyond/monaco/blob/913b009e90bc1747953e30fad4ed4ab19351b548/src/Content/Backend/Solution/Monaco.Template.Backend.Common.Infrastructure/Context/Extensions/FilterExtensions.cs#L163) seems that isn't properly detecting the provided type as valid.

I remember [this PR](https://github.com/onebeyond/monaco/pull/1) was supposed to fix this but seems that it just works with explicit `string?`

Tried different workarounds and got it working with `Guid?` but the workaround made it failing with other nullable types

**Comment by CesarD** [comment]
Some specific scenario? Like with an ` int ` , a ` decimal ` , ` string `  or any other one?

**Comment by Gonzo345** [comment]
> Some specific scenario? Like with an `int` , a `decimal` , `string` or any other one?

Sorry but yeah, I even tried with the latest Monaco release (2.0.1) and modifying the Company entity, adding a `Guid?`, exposing it through the usual GetMappedFields method with no luck. Made some manual adjustments as a workaround but tried with an `int?` and didn't work neither (￣_￣|||)

**Comment by CesarD** [comment]
Can you please confirm if you can reproduce the same by doing it with the ` Address.Street `  or ` Address.County `  fields of the ` Company `  entity being null with the latest version?
Just to ensure that the scenario of the value object is affected as well and to make sure we can use it without having to add a new field to the whole structure to reproduce it.
Thanks!

**Comment by Gonzo345** [comment]
First of all, thank you for your interest and cooperation, as always (✿◡‿◡)

- I can confirm that the `Address` value object is working fine **BUT** just with `string?` types. I tried adding a `long?` inside the `Address` object and it's not working either

So, gathered data is:

1. It works applying filtering to `string?` types and I'm afraid it does due to [this PR](https://github.com/onebeyond/monaco/pull/1)
2. It doesn't work with nullable primitive types like `Guid?`, `int?`, `DateTime?` and so on

In order to help reproducing the issue:

- Screenshot debugging how it validates a `long?` (Population, which is inside the `Address` value object) and fails 
![imagen](https://user-images.githubusercontent.com/4161384/221131763-ff502088-d392-4563-9420-20798ffcad26.png)
- Screenshot debugging how it validates a `Guid?`, a struct property part of `Company` and fails
![imagen](https://user-images.githubusercontent.com/4161384/221131930-8bbbcfbc-3438-4fd1-adb3-234f00681cce.png)
- CompanyExtensions GetMappedFields method: 
```
public staticpublic static Dictionary<string, Expression<Func<Company, object>>> GetMappedFields() =>
		new()
		{
			[nameof(CompanyDto.Id)] = x => x.Id,
			[nameof(CompanyDto.Name)] = x => x.Name,
			[nameof(CompanyDto.Email)] = x => x.Email,
			[nameof(CompanyDto.WebSiteUrl)] = x => x.WebSiteUrl,
			[nameof(CompanyDto.Street)] = x => x.Address!.Street!,
			[nameof(CompanyDto.City)] = x => x.Address!.City!,
			[nameof(CompanyDto.County)] = x => x.Address!.County!,
			[nameof(CompanyDto.PostCode)] = x => x.Address!.PostCode!,
			[nameof(CompanyDto.Population)] = x => x.Address!.Population!,
			[nameof(CompanyDto.CountryId)] = x => x.Address!.CountryId,
			[$"{nameof(CompanyDto.Country)}.{nameof(CountryDto.Name)}"] = x => x.Address!.Country.Name,
			[nameof(CompanyDto.TestId)] = x => x.TestId!,
			[nameof(CompanyDto.Age)] = x => x.Age!,
		};
```
- CompanyEntityConfiguration Configure Method (**Added** nullable `TestId` and `Population`'s `Address`):
 ```
public void Configure(EntityTypeBuilder<Company> builder)
	{
		builder.ConfigureIdWithDbGeneratedValue();

		builder.Property(x => x.Name)
			   .IsRequired(false)
			   .HasMaxLength(100);

		builder.Property(x => x.Email)
			   .IsRequired(false)
			   .HasMaxLength(255);

		builder.Property(x => x.WebSiteUrl)
			   .IsRequired(false)
			   .HasMaxLength(300);

		builder.Property(x => x.TestId)
			   .IsRequired(false);

		builder.Property(x => x.Age)
			   .IsRequired(false);

		builder.Property(x => x.Version)
			   .IsRowVersion();

		builder.OwnsOne(x => x.Address,
						b =>
						{
							b.Property(x => x.Street)
							 .IsRequired(false)
							 .HasMaxLength(100);

							b.Property(x => x.City)
							 .IsRequired(false)
							 .HasMaxLength(100);

							b.Property(x => x.County)
							 .IsRequired(false)
							 .HasMaxLength(100);

							b.Property(x => x.PostCode)
							 .IsRequired(false)
							 .HasMaxLength(10);

							b.Property(x => x.Population)
							 .IsRequired(false);

							b.HasOne(x => x.Country)
							 .WithMany()
							 .HasForeignKey(x => x.CountryId)
							 .IsRequired();
						});
	}
```
- Example row data for testing:
```
[
  {
    "Id": "B786400B-E558-4D5A-D65F-08DB158D1968",
    "Name": "Borja",
    "Email": "borja@borja.com",
    "Version": "AAAAAAAAB9o=",
    "Address_Street": "teststreet",
    "Address_City": "testcity",
    "Address_County": "testcounty",
    "Address_CountryId": "CAD91F44-75F0-4975-82F4-2AB5FC12D9C3",
    "TestId": "7651E645-0060-4EB0-92F4-93360EAF5C69",
    "Address_Population": 85000
  }
]
```
- HTTP requests examples

1. curl --location 'https://localhost:37018/api/v1/companies?County=testcounty' **WORKING**
2. curl --location 'https://localhost:37018/api/v1/companies?testId=7651E645-0060-4EB0-92F4-93360EAF5C69' **NOT WORKING**
3. curl --location 'https://localhost:37018/api/v1/companies?Population=85000' **NOT WORKING**

**Comment by matthewtoghill** [comment]
@Gonzo345 if you change the GetMappedFields method to specify `.Value` for each of the nullable fields e.g. 
`[nameof(CompanyDto.TestId)] = x => x.TestId!.Value` then does that resolve the issue?

Alternatively I think the final else in the GetOperationExpression<T> method can be updated to:

```csharp
        else // Handles all other generic cases (numbers, booleans, etc)
        {
            var underlyingType = Nullable.GetUnderlyingType(type);
            expression = value.ToString().StartsWith('!')
                ? Expression.NotEqual(Expression.Convert(bodyExpression, underlyingType ?? type), Expression.Constant(Convert.ChangeType(value.ToString()[1..], underlyingType ?? type)))
                : Expression.Equal(Expression.Convert(bodyExpression, underlyingType ?? type), Expression.Constant(Convert.ChangeType(value, underlyingType ?? type)));
        }
```

**Comment by CesarD** [comment]
I can confirm that @matthewtoghill's fix works, though I also needed to patch the `ValidateDataType` method as well to perform the `TryParse` for the nullable types too.
Will push a fix soon.
