### ISSUE TITLE
FEATURE: Include .NET Aspire in Backend solution

### ISSUE THREAD

**Issue by CesarD** [onebeyond/monaco#55]
## Detailed Description
Include .NET Aspire orchestration and components as part of the Backend solution.

## Context
Since we want to include multiple other features for making Monaco a cloud-ready app template (like #26, #21 or #22), leveraging something like [.NET Aspire](https://learn.microsoft.com/en-us/dotnet/aspire) can significantly help orchestrate multiple services and also make easier to include some other features like adding health-checks and telemetry, which will greatly improve the monitoring and debugging of such application.
.NET Aspire is also receiving in the short term the possibility to link extra-solution projects, which will greatly help and simplify orchestrate projects from different solutions (and possibly repos, through the use of submodules) that would otherwise could require much more manual work and simplify developing microservices-based applications.

## Possible Implementation
This could be implemented after implementing the forementioned work in previous section.

**Comment by CesarD** [comment]
Well, I was thinking more and more about getting into .NET Aspire, but didn't have a lot of time yet.

The idea was to be able to integrate Aspire into the current solution so we can offer the possibility of launching the solution with the Aspire Dashboard and have both the REST API and the Worker Service reporting their status and logs there (should offer a flag to opt-in during dotnet-new).
Of course, we would need to find a way to decouple the necessary configurations so we don't leak Aspire into the Application layer if possible.

If you feel like getting into it, feel free to do so. Make a fork from your account and start playing around if you want 😉

**Comment by Ture2** [comment]
Ok, great. I'm going to take the Az function template first, I saw Gonzalo was as well assigned 👍

**Comment by Gonzo345** [comment]
> Ok, great. I'm going to take the Az function template first, I saw Gonzalo was as well assigned 👍 

Hey @Ture2 feel free to finish the job or start a brand new branch. I don't exactly remember what or why, but I had some issues with that and pushed the changes to the branch
